export const ActionTypes = {
    SET_BLOGS: "SET_BLOGS",
    SELECTED_BLOGS: "SELECTED_BLOGS",
    REMOVE_SELECTED_BLOGS: "REMOVE_SELECTED_BLOGS",
    DELETE_BLOGS: "DELETE_BLOGS",
    ADD_BLOGS: "ADD_BLOGS"
}